site_name: CUIT ICEC Wiki

# Repository
repo_name: 'cuit_icec/icec_wiki'
repo_url: 'https://gitee.com/cuit_icec/icec_wiki'

nav:
  - 简介:
    - Home: icec/index.md
    - 成员: icec/members.md
    - 比赛以及作品: icec/competition.md
    # - About: about.md
  - MCU:
    - C51: mcu/c51.md
    - STM32: mcu/stm32.md
    - MSP432: mcu/msp432.md
    - ESP32: mcu/esp32.md
    - Node MCU: mcu/node_mcu.md
    - Arduino: mcu/arduino.md
  - 编程语言:
    - C: programming_language/c.md
    - C++: programming_language/cpp.md
    - Python: programming_language/python.md
  - 通讯协议:
    - ONEWIRE: protocol/onewire.md
    - IIC: protocol/iic.md
    - IIS: protocol/iis.md
    - SPI: protocol/spi.md
    - CAN: protocol/can.md
    - UART: protocol/uart.md
    - USB: protocol/usb.md
theme:
  name: 'material'
  language: 'zh'
  include_search_page: false
  search_index_only: true
  features:
    - tabs
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  icon:
    logo: material/book

copyright: 'Copyright &copy; 2020 CUIT ICEC'
site_author: ICEC

extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/contrib/auto-render.min.js'
  - '_static/js/extra.js'

extra_css:
  - 'https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css'

markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
      
  - pymdownx.superfences
  - pymdownx.details
